/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crypto.wallet;

import crypto.wallet.card.CryptoCard;
import crypto.wallet.card.EthereumCard;

import java.io.UnsupportedEncodingException;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.SignatureException;

public class Library {
    public static void main(String[] args) throws InvalidAlgorithmParameterException, NoSuchAlgorithmException, UnsupportedEncodingException, SignatureException, InvalidKeyException {
        CryptoCard card = new EthereumCard();
        String privateKey = card.getPrivateKeyAsBase64();
        String publicKey = card.getPublicKeyAsBase64();

        System.out.println(card.getPrivateKeyAsHex().toLowerCase());
        System.out.println(card.getPublicKeyAsHex().toLowerCase());
        System.out.println(card.getAddress().toLowerCase());
        System.out.println(card.calculateSignatureAsHex("Hello, world").toLowerCase());
    }
}
